### ISSUE TITLE
Take over this work

### ISSUE THREAD

**Issue by wesleytodd** [pkgjs/membership-updater#34]
This is an action to support syncing org teams across github orgs.  It needs to be taken over.  If anyone is interested ping me and I will figure out how to sync on what has been started.

**Comment by wesleytodd** [comment]
@boneskull this is the thing I mentioned to you.  If you are interested we could sync quickly on what I started here (and left in a VERY incomplete state).  Also happy to see you rip it all up and start fresh, but we should have an idea on the shared goals.

**Comment by boneskull** [comment]
I'll take a look at this.

**Comment by boneskull** [comment]
@wesleytodd Maybe we should get a short meeting on the calendar so we can go over what has been done and what's left to do?  I have some questions about the current implementation as well.

also see #36

**Comment by wesleytodd** [comment]
Agreed!  Wonder if any other @pkgjs members would want to participate? Would some time next week work?

**Comment by boneskull** [comment]
@wesleytodd Sounds like no.  Want to set something up for just us then?  Unfortunately I can't share my calendar, but I'm free this week (times PDT):

- tomorrow, 11/3 10a-4p
- 11/4 11a-1p, 2p-4p 
- 11/5 10a-12p, 1p-4p
- 11/6 9a-4p

**Comment by Trott** [comment]
Should this repo be archived? @pkgjs/node-tsc

**Comment by Trott** [comment]
(I'm going to go YOLO-land the open dependabot PRs.)

**Comment by mhdawson** [comment]
@Trott I think it could be archived.

**Comment by Trott** [comment]
I'm going to archive this repo. If that's a mistake, please open a ticket in the nodejs/tsc or nodejs/admin repo. Thanks.
